<template>
  <div class="space-y-6">
    <!-- Report Header -->
    <div class="bg-white rounded-lg border border-gray-200 p-6">
      <div class="flex items-start justify-between">
        <div>
          <h2 class="text-2xl font-bold text-gray-900">{{ report.name }}</h2>
          <p class="text-sm text-gray-600 mt-1">Generated on {{ new Date(report.generatedAt).toLocaleString() }}</p>
          <div class="flex items-center space-x-4 mt-2">
            <span class="inline-flex px-3 py-1 text-sm font-semibold rounded-full bg-blue-100 text-blue-800">
              {{ formatReportType(report.type) }}
            </span>
            <span class="inline-flex px-3 py-1 text-sm font-semibold rounded-full bg-green-100 text-green-800">
              {{ formatPeriod(report.period) }}
            </span>
          </div>
        </div>
        <div class="flex space-x-2">
          <button
            @click="exportReport('pdf')"
            class="px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            <svg class="w-4 h-4 inline-block mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
            </svg>
            Export PDF
          </button>
          <button
            @click="exportReport('excel')"
            class="px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            <svg class="w-4 h-4 inline-block mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 17v1a1 1 0 001 1h4a1 1 0 001-1v-1m-5 0h5m-5 0l-1-4m6 0l-1 4m1-4h.01M13 9h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
            </svg>
            Export Excel
          </button>
          <button
            @click="printReport"
            class="px-3 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
          >
            <svg class="w-4 h-4 inline-block mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" />
            </svg>
            Print
          </button>
        </div>
      </div>
    </div>

    <!-- Date Range Info -->
    <div class="bg-white rounded-lg border border-gray-200 p-4">
      <div class="flex items-center justify-between">
        <div class="flex items-center space-x-2">
          <svg class="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
          </svg>
          <span class="text-sm font-medium text-gray-700">Report Period:</span>
          <span class="text-sm text-gray-900">
            {{ new Date(report.dateFrom).toLocaleDateString() }} - {{ new Date(report.dateTo).toLocaleDateString() }}
          </span>
        </div>
        <div class="text-sm text-gray-500">
          Generated by: {{ report.generatedBy }}
        </div>
      </div>
    </div>

    <!-- Report Content based on Type -->
    <div class="bg-white rounded-lg border border-gray-200">
      <!-- No Data Message -->
      <div v-if="!reportData || Object.keys(reportData).length === 0" class="p-6 text-center">
        <div class="text-gray-500">
          <svg class="w-12 h-12 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
          </svg>
          <p class="text-lg font-medium">No report data available</p>
          <p class="text-sm mt-1">The report may be still generating or there was an issue loading the data.</p>
        </div>
      </div>

      <!-- Production Overview Report -->
      <div v-else-if="isProductionOverview" class="p-6 space-y-6">
        <ProductionOverviewReport :data="reportData" />
      </div>

      <!-- Efficiency Analysis Report -->
      <div v-else-if="isEfficiencyAnalysis" class="p-6 space-y-6">
        <EfficiencyAnalysisReport :data="reportData" />
      </div>

      <!-- Cost Analysis Report -->
      <div v-else-if="isCostAnalysis" class="p-6 space-y-6">
        <CostAnalysisReport :data="reportData" />
      </div>

      <!-- Quality Report -->
      <div v-else-if="isQualityReport" class="p-6 space-y-6">
        <QualityReportView :data="reportData" />
      </div>

      <!-- Resource Utilization Report -->
      <div v-else-if="isResourceUtilization" class="p-6 space-y-6">
        <ResourceUtilizationReport :data="reportData" />
      </div>

      <!-- Material Consumption Report -->
      <div v-else-if="isMaterialConsumption" class="p-6 space-y-6">
        <MaterialConsumptionReport :data="reportData" />
      </div>

      <!-- Generic Report Display -->
      <div v-else class="p-6">
        <GenericReportView :data="report.data" />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import type { ProductionReport } from '../types'
import ProductionOverviewReport from './reports/ProductionOverviewReport.vue'
import EfficiencyAnalysisReport from './reports/EfficiencyAnalysisReport.vue'
import CostAnalysisReport from './reports/CostAnalysisReport.vue'
import QualityReportView from './reports/QualityReportView.vue'
import ResourceUtilizationReport from './reports/ResourceUtilizationReport.vue'
import MaterialConsumptionReport from './reports/MaterialConsumptionReport.vue'
import GenericReportView from './reports/GenericReportView.vue'

interface Props {
  report: ProductionReport
}

const props = defineProps<Props>()

const emit = defineEmits<{
  export: [report: ProductionReport, format: string]
  print: [report: ProductionReport]
  close: []
}>()

// Computed properties for report type checking
const isProductionOverview = computed(() => props.report.type === 'production_overview')
const isEfficiencyAnalysis = computed(() => props.report.type === 'efficiency_analysis')
const isCostAnalysis = computed(() => props.report.type === 'cost_analysis')
const isQualityReport = computed(() => props.report.type === 'quality_report')
const isResourceUtilization = computed(() => props.report.type === 'resource_utilization')
const isMaterialConsumption = computed(() => props.report.type === 'material_consumption')

const reportData = computed(() => props.report?.data || {})

// Helper functions
function formatReportType(type: string): string {
  return type.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}

function formatPeriod(period: string): string {
  return period.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase())
}

function exportReport(format: string) {
  emit('export', props.report, format)
}

function printReport() {
  emit('print', props.report)
  window.print()
}
</script>